library(shiny)

# Define UI for application that draws a histogram
shinyUI(fluidPage(
  titlePanel("R語言與資料科學導論期末展示 Group13"),
  br(),
  sidebarLayout(sidebarPanel(
    h4("旅日人數分析預測"),
    a(strong("Online presentation"),href = "https://huhuman.github.io/Analysis-of-outbound-tourism-statistics/#data_collection"),
    h3(strong("互動模型")),
    helpText("Create demographic maps with information from the 2010 US Census."),
    selectInput("model", 
                label = "Choose a model to display",
                choices = list("Model1" = 1, "Model2" = 2, "Model3" = 3),
                selected = 1),
    
    numericInput("GDP",label = h5("台灣GDP"),value = 0),
    numericInput("NTD2JPY",label = h5("台日匯率"),value = 0),
    numericInput("Taiwan2Others",label = h5("台灣造訪日本以外國家人數"),value = 0),
    numericInput("Youth",label = h5("台灣青少年(0-14)占人口比率"),value = 0),
    numericInput("Workeage",label = h5("台灣青壯年(15-65)占人口比率"),value = 0),
    numericInput("Growth4Japan",label = h5("前一年台灣訪日人數成長率"),value = 0),
    textOutput("Predictor"),
    h3("此Model之參數"),
    strong(textOutput("Index1")),
    strong(textOutput("Index2")),
    strong(textOutput("Index3")),
    strong(textOutput("Index4")),
    br(),
    actionButton("goButton", "Go!"),
    br(),
    p("Click the button to update."),
    h3("預測訪日人數: "),
    strong(textOutput("Result"))
  ),
  mainPanel(
    h3(strong("變因選擇")),
    p("          "),
    h5("1.台日匯率"),
    h5("2.台灣GDP"),
    h5("3.台灣總人口數"),
    h5("4.日本天災發生次數(地震、豪雨)"),
    h5("5.台灣造訪日本以外國家人數"),
    h5("6.台灣年齡結構(分為0-14、15-65、65↑)"),
    h5("7.台灣結婚對數"),
    h5("8.台灣各地氣溫狀況"),
    h5("9.旅日人數成長率"),
    h5("10.台灣造訪日本以外國家人數成長率"),
    br(),
    br(),
    checkboxGroupInput("Index",label = "Index Choose",choices = c("台日匯率" = "NTD2JPY",
                        "台灣GDP" = "TaiwanGDP","台灣總人口數" = "TaiwanPopulation",
                        "日本天災發生次數(地震、豪雨)" = "NaturalDisaster","台灣造訪日本以外國家人數" = "Taiwan2Others",
                        "台灣青少年(0-14)占人口比率" = "Youth","台灣青壯年(15-65)占人口比率" = "Workeage",
                        "台灣老年(65以上)占人口比率" = "Elder","台灣結婚對數" = "Marriage","台灣台北氣溫狀況" = "Taipei_t",
                        "台灣台南氣溫狀況" = "Tainan_t","台灣台中氣溫狀況" = "Taichung",
                        "旅日人數成長率" = "Growth4Japan","台灣造訪日本以外國家人數成長" = "Growth4Others")),
    br(),
    tableOutput("FinalData"),
    br(),
    actionButton("plotButton", "產生分布圖"),
    br(),
    plotOutput("plot"),
    br(),
    h3("Date mining & collection"),
    p("資料來源："),
    p("人文："),
    a(strong("交通部民航局"),href = "http://www.caa.gov.tw/big5/index.asp"),
    br(),
    a(strong("廉航(捷星 樂桃 酷航 虎航 香草)歷史票價查詢"),href = "https://just.bengkuei.me/"),
    br(),
    a(strong("台灣各機場出境/入境人數年(月)統計局"),href = "http://www.immigration.gov.tw/ct.asp?xItem=1322767&ctNode=29699&mp=1"),
    br(),
    a(strong("日本觀光GDP"),href = "http://www.mlit.go.jp/common/000063364.pdf"),
    br(),
    a(strong("中央銀行"),href = "http://www.cbc.gov.tw"),
    br(),
    a(strong("台灣觀光局觀光統計資料庫"),href = "http://stat.taiwan.net.tw/system/cross_sheet_months_DESTINATIONAGESEXUAL.html?=on"),
    br(),
    a(strong("2014年訪日本外國旅客人數簡析"),href = " http://smvv0206.pixnet.net/blog/post/59846656-%5B%E8%A8%8E%E8%AB%96%5D2014%E5%B9%B4%E8%A8%AA%E6%97%A5%E6%9C%AC%E5%A4%96%E5%9C%8B%E6%97%85%E5%AE%A2%E4%BA%BA%E6%95%B8%E7%B0%A1%E6%9E%90"),
    br(),
    a(strong("2015年訪日外國遊客人數，接近2,000萬人的政府目標"),href = "http://www.nippon.com/hk/features/h00132/"),
    br(),
    a(strong("日本旅遊大事記"),href = "http://www.visit-japan.jp/campaign/chronicle/"),
    p("自然："),
    p("1.日本地震："),
    a(strong("http://www.data.jma.go.jp/svd/eqev/data/kyoshin/jishin/index.html"),href = "http://www.data.jma.go.jp/svd/eqev/data/kyoshin/jishin/index.html"),
    a(strong("https://zh.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83"),href = "https://zh.wikipedia.org/wiki/%E6%97%A5%E6%9C%AC%E8%A1%8C%E6%94%BF%E5%8D%80%E5%8A%83"),
    p("2.日本天氣災害"),
    a(strong("http://www.data.jma.go.jp/obd/stats/data/bosai/report/index_1989.html"),href = "http://www.data.jma.go.jp/obd/stats/data/bosai/report/index_1989.html"),
    p("3.日本旅遊警示："),
    a(strong("https://zh.wikipedia.org/wiki/%E5%9C%8B%E5%A4%96%E6%97%85%E9%81%8A%E8%AD%A6%E7%A4%BA%E5%88%86%E7%B4%9A%E8%A1%A8#cite_note-55"),href = "https://zh.wikipedia.org/wiki/%E5%9C%8B%E5%A4%96%E6%97%85%E9%81%8A%E8%AD%A6%E7%A4%BA%E5%88%86%E7%B4%9A%E8%A1%A8#cite_note-55"),
    a(strong("http://www.boca.gov.tw/ct.asp?xItem=4673&amp;ctNode=754&amp;mp=1"),href = "http://www.boca.gov.tw/ct.asp?xItem=4673&amp;ctNode=754&amp;mp=1"),
    p("4.日本登陸的颱風數："),
    a(strong("http://www.data.jma.go.jp/fcd/yoho/typhoon/statistics/landing/landing.html"),href = "http://www.data.jma.go.jp/fcd/yoho/typhoon/statistics/landing/landing.html"),
    p("5.日本各地區梅雨季："),
    a(strong("http://www.data.jma.go.jp/fcd/yoho/baiu/index.html"),href = "http://www.data.jma.go.jp/fcd/yoho/baiu/index.html")
      
  ))
))